spring:
  application:
    name: noname
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: a1b2c3
    url: jdbc:mysql://121.89.212.3:3307/noname?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    #采用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #添加更对数据源配置 需要在configuration里将这些属性赋值给 DruidDateSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    filters: stat,wall

  redis:
    host: 121.89.212.3
    port: 6379
server:
  port: 8080
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

#ql语句日志
logging:
  level:
    com.ybd.noname.dao: debug
#debug: true